### ISSUE TITLE
原版队伍消息不显示

### ISSUE THREAD

**Issue by xxtg666** [Wudji/XPlus-2.0-Modpack#13]
**Game Version**
XPlus PerioTable v6.0.5 based on Minecraft 1.21

**Bug Description**
原版队伍消息不显示

**Steps to Reproduce**
通过 `/teammsg` 发送一条队伍消息

**Expected Behavior**
正常显示队伍消息

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/f1fd8c9b-6e83-495a-841f-66a18c578ff5)
那个空行就是这个命令发出去之后显示的

**Crash Logs (if applicable)**
日志中有报错:
```
[13:00:56] [Render thread/ERROR]: [ChatUtils.modifyMessage] An error occurred while modifying message '-> [aqua] <xxtg666> test', returning original:
[13:00:56] [Render thread/ERROR]: [ChatUtils.modifyMessage] /!\ Please report this error on GitHub or Discord with the full log file attached! /!\
java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147) ~[?:?]
	at net.minecraft.class_5250.method_10852(class_5250.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_5250.method_27693(class_5250.java:56) ~[client-intermediary.jar:?]
	at obro1961.chatpatches.util.ChatUtils.modifyMessage(ChatUtils.java:202) ~[chatpatches-210.6.5.1.jar:?]
	at net.minecraft.class_338.localvar$bge001$chatpatches$modifyMessage(class_338.java:716) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_44811(class_338.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_1812(class_338.java:208) ~[client-intermediary.jar:?]
	at net.minecraft.class_7594.method_44736(class_7594.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_43596(class_634.java:904) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_43631(class_7439.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_11054(class_7439.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?]
[13:00:56] [Render thread/INFO]: [CHAT] 
```

**Additional Information**
删除 `Chat Patches` 模组后正常，但单独安装该模组不会出现该问题。

**Comment by xxtg666** [comment]
v6.0.5.1 好像没有这个问题，可能是有mod冲突了

**Comment by xxtg666** [comment]
已确认，是我加的 No Chat Reports 和 Chat Patches 有不兼容导致的
